import { useRef } from "react";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Copy, Download, Share2, Check } from "lucide-react";
import { BoatSpecData } from "@/hooks/useBoatSpecs";
import { toast } from "sonner";
import { useState } from "react";

interface SpecShareSheetProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  specs: BoatSpecData;
  boatName?: string | null;
  boatMake?: string | null;
  boatModel?: string | null;
  boatYear?: number | null;
}

function formatFeet(ft: number | null): string {
  if (ft === null || ft === undefined) return "—";
  const feet = Math.floor(ft);
  const inches = Math.round((ft - feet) * 12);
  if (inches === 0) return `${feet}'`;
  return `${feet}' ${inches}"`;
}

function formatNumber(val: number | null, unit: string): string {
  if (val === null || val === undefined) return "—";
  return `${val.toLocaleString()} ${unit}`;
}

export function SpecShareSheet({ 
  open, 
  onOpenChange, 
  specs, 
  boatName, 
  boatMake, 
  boatModel, 
  boatYear 
}: SpecShareSheetProps) {
  const [copied, setCopied] = useState(false);
  const specCardRef = useRef<HTMLDivElement>(null);

  const vesselTitle = boatName || `${boatYear || ""} ${boatMake || ""} ${boatModel || ""}`.trim();

  const generateTextSpec = () => {
    const lines = [
      `═══════════════════════════════`,
      `    ${vesselTitle.toUpperCase()}`,
      `    VESSEL SPECIFICATION SHEET`,
      `═══════════════════════════════`,
      ``,
      `DIMENSIONS`,
      `───────────────────────────────`,
      `  LOA:              ${formatFeet(specs.loa_ft)}`,
      `  Beam:             ${formatFeet(specs.beam_ft)}`,
      `  Draft (Up):       ${formatFeet(specs.draft_engines_up_ft)}`,
      `  Draft (Down):     ${formatFeet(specs.draft_engines_down_ft)}`,
      `  Bridge Clearance: ${formatFeet(specs.bridge_clearance_ft)}`,
      `  Dry Weight:       ${formatNumber(specs.dry_weight_lbs, "lbs")}`,
      ``,
      `CAPACITIES`,
      `───────────────────────────────`,
      `  Fuel:             ${formatNumber(specs.fuel_capacity_gal, "gal")}`,
      `  Fresh Water:      ${formatNumber(specs.water_capacity_gal, "gal")}`,
      `  Holding Tank:     ${formatNumber(specs.holding_capacity_gal, "gal")}`,
      specs.livewell_capacity_gal ? `  Livewell:         ${formatNumber(specs.livewell_capacity_gal, "gal")}` : null,
      ``,
      `PERFORMANCE`,
      `───────────────────────────────`,
      `  Cruise Speed:     ${specs.cruise_speed_knots ? `${specs.cruise_speed_knots} kts` : "—"}`,
      `  Max Speed:        ${specs.max_speed_knots ? `${specs.max_speed_knots} kts` : "—"}`,
      `  Hull Type:        ${specs.hull_type || "—"}`,
      specs.max_hp ? `  Max HP:           ${formatNumber(specs.max_hp, "HP")}` : null,
      ``,
      `ELECTRICAL`,
      `───────────────────────────────`,
      `  Battery Type:     ${specs.battery_type || "—"}`,
      `  Battery Count:    ${specs.battery_count || "—"}`,
      `  Shore Power:      ${specs.shore_power || "—"}`,
      specs.battery_locations ? `  Locations:        ${specs.battery_locations}` : null,
      ``,
      `═══════════════════════════════`,
      `  Generated by Boat Genie`,
      `═══════════════════════════════`,
    ].filter(Boolean).join("\n");

    return lines;
  };

  const handleCopyText = async () => {
    const text = generateTextSpec();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Specs copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadText = () => {
    const text = generateTextSpec();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${vesselTitle.replace(/\s+/g, "_")}_Specs.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Spec sheet downloaded");
  };

  const handleShare = async () => {
    const text = generateTextSpec();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${vesselTitle} - Vessel Specs`,
          text: text,
        });
      } catch (err) {
        // User cancelled or share failed, fallback to copy
        await handleCopyText();
      }
    } else {
      await handleCopyText();
    }
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="bottom" className="h-[85vh] rounded-t-xl">
        <SheetHeader className="pb-4">
          <SheetTitle>Share Spec Sheet</SheetTitle>
          <SheetDescription>
            Share your vessel specifications with marinas, mechanics, or haul-out facilities.
          </SheetDescription>
        </SheetHeader>

        {/* Preview Card */}
        <Card ref={specCardRef} className="bg-card border-2 border-primary/20 overflow-hidden mb-6">
          <div className="bg-gradient-to-r from-primary to-primary/80 p-4 text-primary-foreground">
            <h2 className="text-lg font-bold tracking-tight">{vesselTitle}</h2>
            <p className="text-sm opacity-90">Vessel Specification Sheet</p>
          </div>
          
          <CardContent className="p-4 space-y-4 text-sm">
            {/* Dimensions Row */}
            <div className="grid grid-cols-3 gap-3">
              <div className="text-center">
                <p className="text-xs text-muted-foreground uppercase">LOA</p>
                <p className="font-bold text-lg">{formatFeet(specs.loa_ft)}</p>
              </div>
              <div className="text-center border-x border-border">
                <p className="text-xs text-muted-foreground uppercase">Beam</p>
                <p className="font-bold text-lg">{formatFeet(specs.beam_ft)}</p>
              </div>
              <div className="text-center">
                <p className="text-xs text-muted-foreground uppercase">Draft</p>
                <p className="font-bold text-lg">{formatFeet(specs.draft_engines_up_ft)}</p>
              </div>
            </div>

            <Separator />

            {/* Key Stats */}
            <div className="grid grid-cols-2 gap-y-2 gap-x-4">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Bridge Clearance</span>
                <span className="font-medium">{formatFeet(specs.bridge_clearance_ft)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Dry Weight</span>
                <span className="font-medium">{formatNumber(specs.dry_weight_lbs, "lbs")}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Fuel</span>
                <span className="font-medium">{formatNumber(specs.fuel_capacity_gal, "gal")}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Fresh Water</span>
                <span className="font-medium">{formatNumber(specs.water_capacity_gal, "gal")}</span>
              </div>
              {specs.hull_type && (
                <div className="flex justify-between col-span-2">
                  <span className="text-muted-foreground">Hull Type</span>
                  <span className="font-medium">{specs.hull_type}</span>
                </div>
              )}
            </div>

            <div className="text-center pt-2">
              <p className="text-[10px] text-muted-foreground uppercase tracking-widest">
                Generated by Boat Genie
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="grid grid-cols-3 gap-3">
          <Button 
            variant="outline" 
            onClick={handleCopyText}
            className="flex-col h-auto py-4 gap-2"
          >
            {copied ? (
              <Check className="w-5 h-5 text-green-600" />
            ) : (
              <Copy className="w-5 h-5" />
            )}
            <span className="text-xs">Copy Text</span>
          </Button>
          
          <Button 
            variant="outline" 
            onClick={handleDownloadText}
            className="flex-col h-auto py-4 gap-2"
          >
            <Download className="w-5 h-5" />
            <span className="text-xs">Download</span>
          </Button>
          
          <Button 
            variant="default" 
            onClick={handleShare}
            className="flex-col h-auto py-4 gap-2"
          >
            <Share2 className="w-5 h-5" />
            <span className="text-xs">Share</span>
          </Button>
        </div>

        <p className="text-xs text-muted-foreground text-center mt-4">
          The shared spec sheet is a clean, read-only view perfect for texting to service providers.
        </p>
      </SheetContent>
    </Sheet>
  );
}
