
CREATE TABLE public.service_catalog (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  UNIQUE (category, name)
);

INSERT INTO public.service_catalog (category, name) VALUES
  ('Detailing & Cleaning', 'Basic Wash'),
  ('Detailing & Cleaning', 'Full Detail'),
  ('Detailing & Cleaning', 'Wax & Polish'),
  ('Detailing & Cleaning', 'Interior Detail'),
  ('Detailing & Cleaning', 'Engine Room Cleaning'),
  ('Detailing & Cleaning', 'Canvas & Covers Cleaning'),
  ('Detailing & Cleaning', 'Teak Cleaning & Treatment'),
  ('Engines & Propulsion', 'Engine Diagnostic'),
  ('Engines & Propulsion', 'Engine Service'),
  ('Engines & Propulsion', 'Generator Service'),
  ('Engines & Propulsion', 'Propeller Service'),
  ('Engines & Propulsion', 'Transmission Service'),
  ('Engines & Propulsion', 'Winterization / Dewinterization'),
  ('Electrical & Electronics', 'Electrical Diagnostic'),
  ('Electrical & Electronics', 'Battery Service'),
  ('Electrical & Electronics', 'Shore Power & Inverter'),
  ('Electrical & Electronics', 'Navigation Electronics'),
  ('Electrical & Electronics', 'Lighting'),
  ('Electrical & Electronics', 'VHF & Communication'),
  ('Electrical & Electronics', 'Marine Audio'),
  ('Hull, Bottom & Deck', 'Bottom Paint'),
  ('Hull, Bottom & Deck', 'Fiberglass & Gelcoat Repair'),
  ('Hull, Bottom & Deck', 'Waterline Stripe'),
  ('Hull, Bottom & Deck', 'Zinc Replacement'),
  ('Hull, Bottom & Deck', 'Teak Deck Service'),
  ('Hull, Bottom & Deck', 'Deck Hardware Service'),
  ('Hull, Bottom & Deck', 'Nonskid Service'),
  ('Hull, Bottom & Deck', 'Caulking & Sealing'),
  ('Hull, Bottom & Deck', 'Hatch & Port Service'),
  ('Hull, Bottom & Deck', 'Railing & Stanchion Service'),
  ('Hull, Bottom & Deck', 'Windshield Service'),
  ('Plumbing & Water Systems', 'Fresh Water System'),
  ('Plumbing & Water Systems', 'Sanitation & Waste System'),
  ('Plumbing & Water Systems', 'Bilge System'),
  ('Plumbing & Water Systems', 'Pump Service'),
  ('Plumbing & Water Systems', 'Watermaker Service'),
  ('Plumbing & Water Systems', 'Cooling System'),
  ('Plumbing & Water Systems', 'Raw Water System'),
  ('Canvas, Upholstery & Interior', 'Bimini Service'),
  ('Canvas, Upholstery & Interior', 'Enclosure Service'),
  ('Canvas, Upholstery & Interior', 'T-Top Repair'),
  ('Canvas, Upholstery & Interior', 'Upholstery Service'),
  ('Canvas, Upholstery & Interior', 'Custom Canvas Work'),
  ('Rigging & Sails', 'Rigging Inspection'),
  ('Rigging & Sails', 'Standing Rigging'),
  ('Rigging & Sails', 'Running Rigging'),
  ('Rigging & Sails', 'Furling System'),
  ('Rigging & Sails', 'Windlass Service'),
  ('Rigging & Sails', 'Block & Tackle'),
  ('Stabilizers & Steering', 'Gyro Stabilizer Service'),
  ('Stabilizers & Steering', 'Fin Stabilizer Service'),
  ('Stabilizers & Steering', 'Steering System Service'),
  ('Custom Request', 'Custom Request');
